#!/bin/bash
set -e

# =============================================================================
# RKE2 Control Plane Installation Script
# Generated by tdls-easy-k8s
# =============================================================================

# Variables passed from Terraform
CLUSTER_NAME="${cluster_name}"
CLUSTER_TOKEN="${cluster_token}"
RKE2_VERSION="${rke2_version}"
CNI_PLUGIN="${cni_plugin}"
CLUSTER_CIDR="${cluster_cidr}"
SERVICE_CIDR="${service_cidr}"
CLUSTER_DNS="${cluster_dns}"
STATE_BUCKET="${state_bucket}"
NLB_DNS_NAME="${nlb_dns_name}"
IS_FIRST_NODE="${is_first_node}"
FIRST_NODE_IP="${first_node_ip}"
NODE_INDEX="${node_index}"

# =============================================================================
# Logging
# =============================================================================

exec > >(tee /var/log/rke2-install.log)
exec 2>&1

echo "==================================================================="
echo "RKE2 Control Plane Installation"
echo "Cluster: $CLUSTER_NAME"
echo "Node Index: $NODE_INDEX"
echo "First Node: $IS_FIRST_NODE"
echo "==================================================================="

# =============================================================================
# Format and Mount etcd Volume
# =============================================================================

echo "[$(date)] Mounting etcd volume..."

# Wait for the volume to be attached
for i in {1..30}; do
  if [ -b /dev/nvme1n1 ]; then
    echo "Volume found at /dev/nvme1n1"
    break
  fi
  echo "Waiting for volume... ($i/30)"
  sleep 2
done

# Format if not already formatted
if ! blkid /dev/nvme1n1; then
  echo "Formatting etcd volume..."
  mkfs.ext4 /dev/nvme1n1
fi

# Create mount point and mount
mkdir -p /var/lib/rancher/rke2/server/db
mount /dev/nvme1n1 /var/lib/rancher/rke2/server/db

# Add to fstab for persistence
if ! grep -q "/var/lib/rancher/rke2/server/db" /etc/fstab; then
  echo "/dev/nvme1n1 /var/lib/rancher/rke2/server/db ext4 defaults,nofail 0 2" >> /etc/fstab
fi

echo "[$(date)] etcd volume mounted successfully"

# =============================================================================
# Install Dependencies
# =============================================================================

echo "[$(date)] Installing dependencies..."

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl wget jq awscli

# =============================================================================
# Wait for First Node (if not first node)
# =============================================================================

if [ "$IS_FIRST_NODE" != "true" ]; then
  echo "[$(date)] Waiting for first control plane node to be ready..."

  for i in {1..60}; do
    if aws s3 ls "s3://$STATE_BUCKET/kubeconfig/$CLUSTER_NAME/rke2.yaml" 2>/dev/null; then
      echo "[$(date)] First node is ready!"
      break
    fi
    echo "Waiting for first node... ($i/60)"
    sleep 10
  done
fi

# =============================================================================
# Install RKE2
# =============================================================================

echo "[$(date)] Installing RKE2 $RKE2_VERSION..."

curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="$RKE2_VERSION" sh -

echo "[$(date)] RKE2 binaries installed"

# =============================================================================
# Configure RKE2
# =============================================================================

echo "[$(date)] Configuring RKE2..."

mkdir -p /etc/rancher/rke2

# Determine TLS SANs
TLS_SANS=""
if [ -n "$NLB_DNS_NAME" ]; then
  TLS_SANS="  - $NLB_DNS_NAME"
fi

# Get instance private IP
PRIVATE_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
TLS_SANS="$TLS_SANS
  - $PRIVATE_IP"

# Configure based on whether this is the first node
if [ "$IS_FIRST_NODE" = "true" ]; then
  echo "[$(date)] Configuring as first control plane node..."

  cat <<EOF > /etc/rancher/rke2/config.yaml
token: $CLUSTER_TOKEN
node-taint:
  - "node-role.kubernetes.io/control-plane=:NoSchedule"
cluster-cidr: "$CLUSTER_CIDR"
service-cidr: "$SERVICE_CIDR"
cluster-dns: "$CLUSTER_DNS"
cni: $CNI_PLUGIN
disable:
  - rke2-ingress-nginx
etcd-expose-metrics: true
tls-san:
$TLS_SANS
EOF

else
  echo "[$(date)] Configuring to join existing cluster..."

  cat <<EOF > /etc/rancher/rke2/config.yaml
server: https://$FIRST_NODE_IP:9345
token: $CLUSTER_TOKEN
node-taint:
  - "node-role.kubernetes.io/control-plane=:NoSchedule"
tls-san:
$TLS_SANS
EOF

fi

# =============================================================================
# Start RKE2
# =============================================================================

echo "[$(date)] Starting RKE2 server..."

systemctl enable rke2-server.service
systemctl start rke2-server.service

# =============================================================================
# Wait for Cluster to be Ready
# =============================================================================

echo "[$(date)] Waiting for cluster to be ready..."

# Wait for rke2 to create kubeconfig
for i in {1..60}; do
  if [ -f /etc/rancher/rke2/rke2.yaml ]; then
    echo "[$(date)] Kubeconfig created"
    break
  fi
  echo "Waiting for kubeconfig... ($i/60)"
  sleep 5
done

# Wait for nodes to be ready
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
for i in {1..60}; do
  if /var/lib/rancher/rke2/bin/kubectl get nodes 2>/dev/null; then
    echo "[$(date)] Cluster is responding"
    break
  fi
  echo "Waiting for cluster... ($i/60)"
  sleep 5
done

# =============================================================================
# Upload Kubeconfig to S3 (First Node Only)
# =============================================================================

if [ "$IS_FIRST_NODE" = "true" ]; then
  echo "[$(date)] Uploading kubeconfig to S3..."

  # Update server URL in kubeconfig
  cp /etc/rancher/rke2/rke2.yaml /tmp/rke2.yaml

  if [ -n "$NLB_DNS_NAME" ]; then
    sed -i "s/127.0.0.1/$NLB_DNS_NAME/g" /tmp/rke2.yaml
  else
    sed -i "s/127.0.0.1/$PRIVATE_IP/g" /tmp/rke2.yaml
  fi

  aws s3 cp /tmp/rke2.yaml "s3://$STATE_BUCKET/kubeconfig/$CLUSTER_NAME/rke2.yaml"
  rm /tmp/rke2.yaml

  echo "[$(date)] Kubeconfig uploaded successfully"
fi

# =============================================================================
# Install kubectl symlink
# =============================================================================

ln -sf /var/lib/rancher/rke2/bin/kubectl /usr/local/bin/kubectl

# =============================================================================
# Setup Completion Marker
# =============================================================================

touch /var/lib/cloud/instance/rke2-installed

echo "[$(date)] RKE2 control plane installation complete!"
echo "==================================================================="
