#!/bin/bash
set -e

# =============================================================================
# RKE2 Control Plane Installation Script (Proxmox VE)
# Generated by tdls-easy-k8s
# =============================================================================

# Variables passed from Terraform
CLUSTER_NAME="${cluster_name}"
CLUSTER_TOKEN="${cluster_token}"
RKE2_VERSION="${rke2_version}"
CNI_PLUGIN="${cni_plugin}"
CLUSTER_CIDR="${cluster_cidr}"
SERVICE_CIDR="${service_cidr}"
CLUSTER_DNS="${cluster_dns}"
VIP_ADDRESS="${vip_address}"
IS_FIRST_NODE="${is_first_node}"
FIRST_NODE_IP="${first_node_ip}"
NODE_INDEX="${node_index}"
SSH_PUBLIC_KEY="${ssh_public_key}"

# =============================================================================
# Logging
# =============================================================================

exec > >(tee /var/log/rke2-install.log)
exec 2>&1

echo "==================================================================="
echo "RKE2 Control Plane Installation (Proxmox VE)"
echo "Cluster: $CLUSTER_NAME"
echo "Node Index: $NODE_INDEX"
echo "First Node: $IS_FIRST_NODE"
echo "VIP: $VIP_ADDRESS"
echo "==================================================================="

# =============================================================================
# SSH Access
# =============================================================================

echo "[$(date)] Setting up SSH access..."
mkdir -p /root/.ssh
echo "$SSH_PUBLIC_KEY" >> /root/.ssh/authorized_keys
chmod 700 /root/.ssh
chmod 600 /root/.ssh/authorized_keys
sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
systemctl restart sshd

# =============================================================================
# Install Dependencies
# =============================================================================

echo "[$(date)] Installing dependencies..."

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl wget jq qemu-guest-agent

# Start guest agent (for Terraform IP detection)
systemctl enable qemu-guest-agent
systemctl start qemu-guest-agent

# =============================================================================
# Detect Node IP (interface-based, no metadata API)
# =============================================================================

echo "[$(date)] Detecting node IP..."

NODE_IP=""
IFACE_NAME=""
for iface in eth0 ens18 ens19 enp0s18 enp1s0; do
  IP=$(ip -4 addr show "$iface" 2>/dev/null | grep -oP '(?<=inet )\d+\.\d+\.\d+\.\d+' | head -1)
  if [ -n "$IP" ] && [ "$IP" != "127.0.0.1" ]; then
    NODE_IP="$IP"
    IFACE_NAME="$iface"
    break
  fi
done

if [ -z "$NODE_IP" ]; then
  NODE_IP=$(hostname -I | awk '{print $1}')
  IFACE_NAME=$(ip route | grep default | awk '{print $5}' | head -1)
fi

echo "[$(date)] Node IP: $NODE_IP (interface: $IFACE_NAME)"

# =============================================================================
# Wait for First Node (if not first node)
# =============================================================================

if [ "$IS_FIRST_NODE" != "true" ]; then
  echo "[$(date)] Waiting for first control plane node to be ready..."

  for i in {1..120}; do
    if curl -k -s -o /dev/null -w "%%{http_code}" "https://$FIRST_NODE_IP:9345/cacerts" 2>/dev/null | grep -q "200"; then
      echo "[$(date)] First node is ready!"
      break
    fi
    echo "Waiting for first node... ($i/120)"
    sleep 10
  done
fi

# =============================================================================
# Install RKE2
# =============================================================================

echo "[$(date)] Installing RKE2 $RKE2_VERSION..."

curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="$RKE2_VERSION" sh -

echo "[$(date)] RKE2 binaries installed"

# =============================================================================
# Configure RKE2
# =============================================================================

echo "[$(date)] Configuring RKE2..."

mkdir -p /etc/rancher/rke2

if [ "$IS_FIRST_NODE" = "true" ]; then
  echo "[$(date)] Configuring as first control plane node..."

  cat <<EOF > /etc/rancher/rke2/config.yaml
token: $CLUSTER_TOKEN
node-ip: $NODE_IP
node-taint:
  - "node-role.kubernetes.io/control-plane=:NoSchedule"
cluster-cidr: "$CLUSTER_CIDR"
service-cidr: "$SERVICE_CIDR"
cluster-dns: "$CLUSTER_DNS"
cni: $CNI_PLUGIN
disable:
  - rke2-ingress-nginx
etcd-expose-metrics: true
tls-san:
  - $NODE_IP
  - $VIP_ADDRESS
  - 127.0.0.1
EOF

else
  echo "[$(date)] Configuring to join existing cluster..."

  cat <<EOF > /etc/rancher/rke2/config.yaml
server: https://$FIRST_NODE_IP:9345
token: $CLUSTER_TOKEN
node-ip: $NODE_IP
node-taint:
  - "node-role.kubernetes.io/control-plane=:NoSchedule"
tls-san:
  - $NODE_IP
  - $VIP_ADDRESS
  - 127.0.0.1
EOF

fi

# =============================================================================
# kube-vip Static Pod (API load balancing via ARP)
# =============================================================================

echo "[$(date)] Setting up kube-vip static pod..."

mkdir -p /var/lib/rancher/rke2/server/manifests

cat <<EOF > /var/lib/rancher/rke2/server/manifests/kube-vip.yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - name: kube-vip
    image: ghcr.io/kube-vip/kube-vip:v0.8.9
    imagePullPolicy: IfNotPresent
    args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: "$IFACE_NAME"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: "$VIP_ADDRESS"
    - name: prometheus_server
      value: ":2112"
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/rancher/rke2/rke2.yaml
    name: kubeconfig
EOF

# =============================================================================
# Start RKE2
# =============================================================================

echo "[$(date)] Starting RKE2 server..."

systemctl enable rke2-server.service
systemctl start rke2-server.service

# =============================================================================
# Wait for Cluster to be Ready
# =============================================================================

echo "[$(date)] Waiting for cluster to be ready..."

for i in {1..60}; do
  if [ -f /etc/rancher/rke2/rke2.yaml ]; then
    echo "[$(date)] Kubeconfig created"
    break
  fi
  echo "Waiting for kubeconfig... ($i/60)"
  sleep 5
done

export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
for i in {1..60}; do
  if /var/lib/rancher/rke2/bin/kubectl get nodes 2>/dev/null; then
    echo "[$(date)] Cluster is responding"
    break
  fi
  echo "Waiting for cluster... ($i/60)"
  sleep 5
done

# =============================================================================
# Install kubectl symlink
# =============================================================================

ln -sf /var/lib/rancher/rke2/bin/kubectl /usr/local/bin/kubectl

# =============================================================================
# Setup Completion Marker
# =============================================================================

touch /var/lib/cloud/instance/rke2-installed

echo "[$(date)] RKE2 control plane installation complete!"
echo "==================================================================="
