#!/bin/bash
set -e

# =============================================================================
# RKE2 Worker Node Installation Script (Proxmox VE)
# Generated by tdls-easy-k8s
# =============================================================================

# Variables passed from Terraform
CLUSTER_NAME="${cluster_name}"
CLUSTER_TOKEN="${cluster_token}"
RKE2_VERSION="${rke2_version}"
VIP_ADDRESS="${vip_address}"
FIRST_NODE_IP="${first_node_ip}"
NODE_INDEX="${node_index}"
SSH_PUBLIC_KEY="${ssh_public_key}"

# =============================================================================
# Logging
# =============================================================================

exec > >(tee /var/log/rke2-install.log)
exec 2>&1

echo "==================================================================="
echo "RKE2 Worker Node Installation (Proxmox VE)"
echo "Cluster: $CLUSTER_NAME"
echo "Node Index: $NODE_INDEX"
echo "API Endpoint: $FIRST_NODE_IP"
echo "==================================================================="

# =============================================================================
# SSH Access
# =============================================================================

echo "[$(date)] Setting up SSH access..."
mkdir -p /root/.ssh
echo "$SSH_PUBLIC_KEY" >> /root/.ssh/authorized_keys
chmod 700 /root/.ssh
chmod 600 /root/.ssh/authorized_keys
sed -i 's/^#*PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
systemctl restart sshd

# =============================================================================
# Install Dependencies
# =============================================================================

echo "[$(date)] Installing dependencies..."

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl wget jq qemu-guest-agent

# Start guest agent (for Terraform IP detection)
systemctl enable qemu-guest-agent
systemctl start qemu-guest-agent

# =============================================================================
# Detect Node IP (interface-based, no metadata API)
# =============================================================================

echo "[$(date)] Detecting node IP..."

NODE_IP=""
for iface in eth0 ens18 ens19 enp0s18 enp1s0; do
  IP=$(ip -4 addr show "$iface" 2>/dev/null | grep -oP '(?<=inet )\d+\.\d+\.\d+\.\d+' | head -1)
  if [ -n "$IP" ] && [ "$IP" != "127.0.0.1" ]; then
    NODE_IP="$IP"
    break
  fi
done

if [ -z "$NODE_IP" ]; then
  NODE_IP=$(hostname -I | awk '{print $1}')
fi

echo "[$(date)] Node IP: $NODE_IP"

# =============================================================================
# Wait for API Server to be Available
# =============================================================================

echo "[$(date)] Waiting for RKE2 registration endpoint to be available..."

for i in {1..120}; do
  if curl -k -s -o /dev/null -w "%%{http_code}" "https://$FIRST_NODE_IP:9345/cacerts" 2>/dev/null | grep -q "200"; then
    echo "[$(date)] RKE2 registration endpoint is ready!"
    break
  fi
  echo "Waiting for registration endpoint... ($i/120)"
  sleep 10
done

# =============================================================================
# Install RKE2 Agent
# =============================================================================

echo "[$(date)] Installing RKE2 agent $RKE2_VERSION..."

curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" INSTALL_RKE2_VERSION="$RKE2_VERSION" sh -

echo "[$(date)] RKE2 agent binaries installed"

# =============================================================================
# Configure RKE2 Agent
# =============================================================================

echo "[$(date)] Configuring RKE2 agent..."

mkdir -p /etc/rancher/rke2

cat <<EOF > /etc/rancher/rke2/config.yaml
server: https://$FIRST_NODE_IP:9345
token: $CLUSTER_TOKEN
node-ip: $NODE_IP
EOF

# =============================================================================
# Start RKE2 Agent
# =============================================================================

echo "[$(date)] Starting RKE2 agent..."

systemctl enable rke2-agent.service
systemctl start rke2-agent.service

# =============================================================================
# Wait for Node to be Ready
# =============================================================================

echo "[$(date)] Waiting for node to register with cluster..."

for i in {1..60}; do
  if systemctl is-active --quiet rke2-agent; then
    echo "[$(date)] RKE2 agent is running"
    break
  fi
  echo "Waiting for agent... ($i/60)"
  sleep 5
done

# =============================================================================
# Install kubectl symlink
# =============================================================================

ln -sf /var/lib/rancher/rke2/bin/kubectl /usr/local/bin/kubectl

# =============================================================================
# Setup Completion Marker
# =============================================================================

touch /var/lib/cloud/instance/rke2-installed

echo "[$(date)] RKE2 worker node installation complete!"
echo "==================================================================="
