#!/bin/bash
set -e

# =============================================================================
# RKE2 Worker Node Installation Script (Hetzner Cloud)
# Generated by tdls-easy-k8s
# =============================================================================

# Variables passed from Terraform
CLUSTER_NAME="${cluster_name}"
CLUSTER_TOKEN="${cluster_token}"
RKE2_VERSION="${rke2_version}"
API_ENDPOINT="${api_endpoint}"
NODE_INDEX="${node_index}"

# =============================================================================
# Logging
# =============================================================================

exec > >(tee /var/log/rke2-install.log)
exec 2>&1

echo "==================================================================="
echo "RKE2 Worker Node Installation (Hetzner)"
echo "Cluster: $CLUSTER_NAME"
echo "Node Index: $NODE_INDEX"
echo "API Endpoint: $API_ENDPOINT"
echo "==================================================================="

# =============================================================================
# Install Dependencies
# =============================================================================

echo "[$(date)] Installing dependencies..."

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl wget jq

# =============================================================================
# Wait for API Server to be Available
# =============================================================================

echo "[$(date)] Waiting for RKE2 registration endpoint to be available..."

for i in {1..120}; do
  if curl -k -s -o /dev/null -w "%%{http_code}" "https://$API_ENDPOINT:9345/cacerts" 2>/dev/null | grep -q "200"; then
    echo "[$(date)] RKE2 registration endpoint is ready!"
    break
  fi
  echo "Waiting for registration endpoint... ($i/120)"
  sleep 10
done

# =============================================================================
# Install RKE2 Agent
# =============================================================================

echo "[$(date)] Installing RKE2 agent $RKE2_VERSION..."

curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" INSTALL_RKE2_VERSION="$RKE2_VERSION" sh -

echo "[$(date)] RKE2 agent binaries installed"

# =============================================================================
# Configure RKE2 Agent
# =============================================================================

echo "[$(date)] Configuring RKE2 agent..."

mkdir -p /etc/rancher/rke2

# Get server metadata for node labels
PUBLIC_IP=$(curl -s http://169.254.169.254/hetzner/v1/metadata/public-ipv4 2>/dev/null || hostname -I | awk '{print $1}')
LOCATION=$(curl -s http://169.254.169.254/hetzner/v1/metadata/availability-zone 2>/dev/null || echo "unknown")
SERVER_TYPE=$(curl -s http://169.254.169.254/hetzner/v1/metadata/instance-id 2>/dev/null || echo "unknown")

cat <<EOF > /etc/rancher/rke2/config.yaml
server: https://$API_ENDPOINT:9345
token: $CLUSTER_TOKEN
node-label:
  - "topology.kubernetes.io/zone=$LOCATION"
  - "node.tdls-easy-k8s.io/public-ip=$PUBLIC_IP"
EOF

# =============================================================================
# Start RKE2 Agent
# =============================================================================

echo "[$(date)] Starting RKE2 agent..."

systemctl enable rke2-agent.service
systemctl start rke2-agent.service

# =============================================================================
# Wait for Node to be Ready
# =============================================================================

echo "[$(date)] Waiting for node to register with cluster..."

for i in {1..60}; do
  if systemctl is-active --quiet rke2-agent; then
    echo "[$(date)] RKE2 agent is running"
    break
  fi
  echo "Waiting for agent... ($i/60)"
  sleep 5
done

# =============================================================================
# Install kubectl symlink
# =============================================================================

ln -sf /var/lib/rancher/rke2/bin/kubectl /usr/local/bin/kubectl

# =============================================================================
# Setup Completion Marker
# =============================================================================

touch /var/lib/cloud/instance/rke2-installed

echo "[$(date)] RKE2 worker node installation complete!"
echo "==================================================================="
