#!/bin/bash
set -e

# =============================================================================
# RKE2 Control Plane Installation Script (Hetzner Cloud)
# Generated by tdls-easy-k8s
# =============================================================================

# Variables passed from Terraform
CLUSTER_NAME="${cluster_name}"
CLUSTER_TOKEN="${cluster_token}"
RKE2_VERSION="${rke2_version}"
CNI_PLUGIN="${cni_plugin}"
CLUSTER_CIDR="${cluster_cidr}"
SERVICE_CIDR="${service_cidr}"
CLUSTER_DNS="${cluster_dns}"
LB_IPV4="${lb_ipv4}"
IS_FIRST_NODE="${is_first_node}"
FIRST_NODE_IP="${first_node_ip}"
NODE_INDEX="${node_index}"

# =============================================================================
# Logging
# =============================================================================

exec > >(tee /var/log/rke2-install.log)
exec 2>&1

echo "==================================================================="
echo "RKE2 Control Plane Installation (Hetzner)"
echo "Cluster: $CLUSTER_NAME"
echo "Node Index: $NODE_INDEX"
echo "First Node: $IS_FIRST_NODE"
echo "LB IP: $LB_IPV4"
echo "==================================================================="

# =============================================================================
# Install Dependencies
# =============================================================================

echo "[$(date)] Installing dependencies..."

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl wget jq

# =============================================================================
# Wait for First Node (if not first node)
# =============================================================================

if [ "$IS_FIRST_NODE" != "true" ]; then
  echo "[$(date)] Waiting for first control plane node to be ready..."

  for i in {1..120}; do
    if curl -k -s -o /dev/null -w "%%{http_code}" "https://$FIRST_NODE_IP:9345/cacerts" 2>/dev/null | grep -q "200"; then
      echo "[$(date)] First node is ready!"
      break
    fi
    echo "Waiting for first node... ($i/120)"
    sleep 10
  done
fi

# =============================================================================
# Install RKE2
# =============================================================================

echo "[$(date)] Installing RKE2 $RKE2_VERSION..."

curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="$RKE2_VERSION" sh -

echo "[$(date)] RKE2 binaries installed"

# =============================================================================
# Configure RKE2
# =============================================================================

echo "[$(date)] Configuring RKE2..."

mkdir -p /etc/rancher/rke2

# Get server IPs
# Private IP from Hetzner private network (not eth0 — that's the public interface)
PRIVATE_IP=$(curl -s http://169.254.169.254/hetzner/v1/metadata/private-networks | grep -oP '(?<=ip: )\S+' | head -1)
PUBLIC_IP=$(curl -s http://169.254.169.254/hetzner/v1/metadata/public-ipv4 2>/dev/null || hostname -I | awk '{print $1}')

if [ -z "$PRIVATE_IP" ]; then
  echo "[$(date)] WARNING: Could not detect private network IP, falling back to public IP"
  PRIVATE_IP="$PUBLIC_IP"
fi
echo "[$(date)] Private IP: $PRIVATE_IP, Public IP: $PUBLIC_IP"

# Configure Canal to use the private network interface for VXLAN overlay.
# Without this, Flannel auto-detects via default route (public interface),
# and VXLAN traffic gets blocked by the firewall which only allows it from
# the private network CIDR.
mkdir -p /var/lib/rancher/rke2/server/manifests
cat <<EOF > /var/lib/rancher/rke2/server/manifests/rke2-canal-config.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-canal
  namespace: kube-system
spec:
  valuesContent: |-
    flannel:
      iface: enp7s0
EOF

# Build TLS SANs
if [ "$IS_FIRST_NODE" = "true" ]; then
  echo "[$(date)] Configuring as first control plane node..."

  cat <<EOF > /etc/rancher/rke2/config.yaml
token: $CLUSTER_TOKEN
node-ip: $PRIVATE_IP
node-taint:
  - "node-role.kubernetes.io/control-plane=:NoSchedule"
cluster-cidr: "$CLUSTER_CIDR"
service-cidr: "$SERVICE_CIDR"
cluster-dns: "$CLUSTER_DNS"
cni: $CNI_PLUGIN
disable:
  - rke2-ingress-nginx
etcd-expose-metrics: true
tls-san:
  - $PUBLIC_IP
  - $PRIVATE_IP
  - $LB_IPV4
EOF

else
  echo "[$(date)] Configuring to join existing cluster..."

  cat <<EOF > /etc/rancher/rke2/config.yaml
server: https://$FIRST_NODE_IP:9345
token: $CLUSTER_TOKEN
node-ip: $PRIVATE_IP
node-taint:
  - "node-role.kubernetes.io/control-plane=:NoSchedule"
tls-san:
  - $PUBLIC_IP
  - $PRIVATE_IP
  - $LB_IPV4
EOF

fi

# =============================================================================
# Start RKE2
# =============================================================================

echo "[$(date)] Starting RKE2 server..."

systemctl enable rke2-server.service
systemctl start rke2-server.service

# =============================================================================
# Wait for Cluster to be Ready
# =============================================================================

echo "[$(date)] Waiting for cluster to be ready..."

for i in {1..60}; do
  if [ -f /etc/rancher/rke2/rke2.yaml ]; then
    echo "[$(date)] Kubeconfig created"
    break
  fi
  echo "Waiting for kubeconfig... ($i/60)"
  sleep 5
done

export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
for i in {1..60}; do
  if /var/lib/rancher/rke2/bin/kubectl get nodes 2>/dev/null; then
    echo "[$(date)] Cluster is responding"
    break
  fi
  echo "Waiting for cluster... ($i/60)"
  sleep 5
done

# =============================================================================
# Install kubectl symlink
# =============================================================================

ln -sf /var/lib/rancher/rke2/bin/kubectl /usr/local/bin/kubectl

# =============================================================================
# Setup Completion Marker
# =============================================================================

touch /var/lib/cloud/instance/rke2-installed

echo "[$(date)] RKE2 control plane installation complete!"
echo "==================================================================="
