#!/bin/bash
set -e

# =============================================================================
# RKE2 Worker Node Installation Script
# Generated by tdls-easy-k8s
# =============================================================================

# Variables passed from Terraform
CLUSTER_NAME="${cluster_name}"
CLUSTER_TOKEN="${cluster_token}"
RKE2_VERSION="${rke2_version}"
API_ENDPOINT="${api_endpoint}"
NODE_INDEX="${node_index}"

# =============================================================================
# Logging
# =============================================================================

exec > >(tee /var/log/rke2-install.log)
exec 2>&1

echo "==================================================================="
echo "RKE2 Worker Node Installation"
echo "Cluster: $CLUSTER_NAME"
echo "Node Index: $NODE_INDEX"
echo "API Endpoint: $API_ENDPOINT"
echo "==================================================================="

# =============================================================================
# Install Dependencies
# =============================================================================

echo "[$(date)] Installing dependencies..."

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl wget jq

# =============================================================================
# Wait for API Server to be Available
# =============================================================================

echo "[$(date)] Waiting for Kubernetes API server to be available..."

for i in {1..120}; do
  if curl -k -s "https://$API_ENDPOINT:6443/healthz" 2>/dev/null | grep -q "ok"; then
    echo "[$(date)] API server is ready!"
    break
  fi
  echo "Waiting for API server... ($i/120)"
  sleep 10
done

# =============================================================================
# Install RKE2 Agent
# =============================================================================

echo "[$(date)] Installing RKE2 agent $RKE2_VERSION..."

curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" INSTALL_RKE2_VERSION="$RKE2_VERSION" sh -

echo "[$(date)] RKE2 agent binaries installed"

# =============================================================================
# Configure RKE2 Agent
# =============================================================================

echo "[$(date)] Configuring RKE2 agent..."

mkdir -p /etc/rancher/rke2

# Get instance metadata
INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
INSTANCE_TYPE=$(curl -s http://169.254.169.254/latest/meta-data/instance-type)
AVAILABILITY_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
REGION=$(echo $AVAILABILITY_ZONE | sed 's/[a-z]$//')

cat <<EOF > /etc/rancher/rke2/config.yaml
server: https://$API_ENDPOINT:6443
token: $CLUSTER_TOKEN
node-label:
  - "node.kubernetes.io/instance-type=$INSTANCE_TYPE"
  - "topology.kubernetes.io/zone=$AVAILABILITY_ZONE"
  - "topology.kubernetes.io/region=$REGION"
  - "node.tdls-easy-k8s.io/instance-id=$INSTANCE_ID"
EOF

# =============================================================================
# Start RKE2 Agent
# =============================================================================

echo "[$(date)] Starting RKE2 agent..."

systemctl enable rke2-agent.service
systemctl start rke2-agent.service

# =============================================================================
# Wait for Node to be Ready
# =============================================================================

echo "[$(date)] Waiting for node to register with cluster..."

for i in {1..60}; do
  if systemctl is-active --quiet rke2-agent; then
    echo "[$(date)] RKE2 agent is running"
    break
  fi
  echo "Waiting for agent... ($i/60)"
  sleep 5
done

# =============================================================================
# Install kubectl symlink
# =============================================================================

ln -sf /var/lib/rancher/rke2/bin/kubectl /usr/local/bin/kubectl

# =============================================================================
# Setup Completion Marker
# =============================================================================

touch /var/lib/cloud/instance/rke2-installed

echo "[$(date)] RKE2 worker node installation complete!"
echo "==================================================================="
