# ClusterSecretStore for AWS Secrets Manager
# Uses worker node IAM instance profile for authentication (no credentials needed)
# Change the region to match your cluster's region
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1  # change to your region
