# ClusterSecretStore for in-cluster Vault (deploy mode)
# Points at the Vault service deployed in vault-system namespace
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: http://vault-system-vault.vault-system.svc:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
