# ClusterSecretStore for external Vault
# Uses Kubernetes auth — configure Vault with:
#   vault auth enable kubernetes
#   vault write auth/kubernetes/config kubernetes_host="https://<k8s-api>:6443"
#   vault write auth/kubernetes/role/external-secrets \
#     bound_service_account_names=external-secrets \
#     bound_service_account_namespaces=external-secrets \
#     policies=default
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: https://vault.example.com  # change to your Vault address
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
